services:
  juice-shop:
    build:
      context: ./juice-shop
      dockerfile: ./Dockerfile-juice-shop
    container_name: juice-shop
    restart: always
    ports:
      - "3000:3000"
    networks:
      - app-network

  zap-server:
    build:
      context: .
      dockerfile: Dockerfile-zap
    container_name: zap-server
    restart: always
    ports:
      - "8090:8090"
    networks:
      - app-network
    volumes:
      - zap_reports:/zap/wrk

  sonarqube:
    image: sonarqube:lts-community
    container_name: sonarqube
    depends_on:
      - db-sonarqube
    ports:
      - "9000:9000"
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db-sonarqube:5432/sonarqube
      SONAR_JDBC_USERNAME: sonarqube
      SONAR_JDBC_PASSWORD: ainsurev
      JAVA_HOME: /usr/lib/jvm/java-11-openjdk-amd64
      ES_JAVA_HOME: /usr/lib/jvm/java-11-openjdk-amd64
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    networks:
      - app-network

  db-sonarqube:
    image: postgres:12
    container_name: db-sonarqube
    environment:
      POSTGRES_USER: sonarqube
      POSTGRES_PASSWORD: ainsurev
    ports:
      - "5432:5432"
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
    networks:
      - app-network

  jenkins:
    build:
      context: .
      dockerfile: Dockerfile-jenkins
    container_name: jenkins
    restart: always
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins_dependency_check:/srv/dependency-check
      - zap_reports:/zap/wrk
    environment:
      JAVA_OPTS: >
        -Djenkins.install.runSetupWizard=false
        -Dhttp.keepAliveTimeout=600000
        -Dhttp.socketTimeout=600000
      DOCKER_GROUP_ID: "988"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  zap_reports:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  postgresql:
  postgresql_data:
  jenkins_home:
  jenkins_dependency_check:
