# Use the official OWASP ZAP stable image as a base
FROM zaproxy/zap-stable

# Set working directory inside the container
WORKDIR /zap

# Define the entrypoint script
ENTRYPOINT ["sh", "-c", "echo 'Starting ZAP server...'; \
    zap.sh -daemon -port 8090 -host 0.0.0.0 \
    -config api.disablekey=true \
    -config api.addrs.addr.name=.* \
    -config api.addrs.addr.regex=true"]